### ISSUE TITLE
Compilation issue with stan 2.30.0

### ISSUE THREAD

**Issue by seabbs** [epiforecasts/epinowcast#105]
I am seeing a compilation error both locally and on the CI when using `develop` and  in #112 . This happens with all model versions so I think is a breaking change from `cmdstan 2.30.0` which I haven't been able to get to the bottom of yet rather than a model-specific issue. 

Confirmation if others are seeing this would be useful. If this issue impacts `main` as well (which I think likely) then any fix needs to be targetted there as well. 

_Originally posted by @seabbs in https://github.com/epiforecasts/epinowcast/issues/103#issuecomment-1176733477_

**Comment by seabbs** [comment]
This also fails, 

```r
enw_model("inst/stan/epinowcast.stan", include = "inst/stan")
```

**Comment by seabbs** [comment]
Looking at the issues for `cmdstanr` and `cmdstan` I see nothing related. I also see nothing related in the  `cmdstan 2.30.0` release notes.

**Comment by seabbs** [comment]
Rolling back to `cmdstan 2.29.0` I see successful compilation using,

```r
cmdstanr::install_cmdstan(version = "2.29.0")
enw_model()
```

**Comment by seabbs** [comment]
To resolve this in the CI `cmdstan` has been pinned to `2.29.0` any updates looking to fix this should roll this back.

**Comment by seabbs** [comment]
I still haven't gotten to the bottom of this.

**Comment by sbfnk** [comment]
For me,
`enw_model(stanc_options = list())` 
works while
`enw_model()`
yields an error so it seems to be related to the optimisation (looks like a `cmdstan` error to me)

**Comment by seabbs** [comment]
ah, that is good to know. For now, we can just drop passing optimisation as it only gave a very small speed up anyway.

**Comment by seabbs** [comment]
Done in #117
