### ISSUE TITLE
Links in NEWS.md

### ISSUE THREAD

**Issue by seabbs** [epiforecasts/epinowcast#118]
In order to track development, we have been using a news file where each change/feature is described using a bullet point. In these bullet points we generally link to the issue (using the #number system used by GitHub) and highlight who contributed to the PR (using the @author GitHub tag). Up until now we have manually created markdown links for these but GitHub already automatically does this. It turns out that `pkgdown` which is the other entry point to our documentation also does this automatically. 

This means that we could streamline our documentation by removing the markdown links and allowing GitHub/`pkgdown` to do this for us. It does mean that users reading our NEWS.md locally or from another hosting provider won't have links so potentially worth considering if we want to do this.

**Comment by choi-hannah** [comment]
Hi I'm happy to help with this

**Comment by seabbs** [comment]
Amazing, thanks! The first step is to have a look at the [contributing guide](https://github.com/epiforecasts/epinowcast/blob/main/CONTRIBUTING.md). Give me a ping if you come across any issues.

**Comment by seabbs** [comment]
Closed in #132 by @choi-hannah 🥳
