### ISSUE TITLE
Bug: When profile = TRUE generated quantities are not present

### ISSUE THREAD

**Issue by seabbs** [epiforecasts/epinowcast#44]
When `profile = TRUE` and profiling is in use as introduced in #10 then generated quantities are no longer stored. This means that nowcasts etc do not exist and plotting is not possible. As this feature is only used during development for a limited range of purposes this is not a must fix. Flagging @adrian-lison who implemented #10 and may have some insights. 

The problem can be seen by running the readme example code with `profile = TRUE` in `enw_model`.

**Comment by adrian-lison** [comment]
Thanks, this must be a problem with the profiling statements I added to the generated quantities in hindsight, without further checking, I admit. I will have a look at it.

**Comment by adrian-lison** [comment]
Learned something again: Don't put profiling statements before variable declarations. That was the problem in the generated quantities.

**Comment by seabbs** [comment]
That is good to know.
