### ISSUE TITLE
Warnings at initialisation for complex models

### ISSUE THREAD

**Issue by seabbs** [epiforecasts/epinowcast#6]
Currently, there are warnings thrown when models become complex. This could indicate an issue and so the investigation is needed to try and resolve this.

**Comment by adrian-lison** [comment]
Do you mean warnings during warm-up (like `inf`, `nan` or violations of `lower`/`upper` limits for certain model parameters)?

**Comment by seabbs** [comment]
Yes exactly.

**Comment by seabbs** [comment]
#65 tries to reduce these issues by keeping more of the computation on the log scale.
