### ISSUE TITLE
New title and DESCRIPTION

### ISSUE THREAD

**Issue by seabbs** [epiforecasts/epinowcast#72]
The package's current title is not really correct as what is being correct is not censoring but truncation. It seems like there are better titles available especially as the package expands into being a more general real-time analysis toolkit. At the same time it makes sense to update the package description (found in both the DESCRIPTION file and at the beginning of the README) to match this new title.

**Comment by adrian-lison** [comment]
Maybe a point for discussion: As other use cases could be tackled with epinowcast as well: do we want to focus on epidemiological data in the description? I know that the name epinowcast already sets the stage and maybe it is most important to focus on the main intended user group (especially as we may add more epidemiological expectation models in the future). Just wanted to bring it up once.

**Comment by adrian-lison** [comment]
Should we maybe just drop the "right-truncated/censored". This is how I understand the core idea of nowcasting as a technique, so it is a bit of a redundancy? And I would expect people who understand right truncation in count data to also know about nowcasting?

**Comment by seabbs** [comment]
> 

Yeah, this is a good point as you are right it is quite general. Personally, I think tailoring the tool for this audience does make sense and so would perhaps keep it as a focus. 



> Should we maybe just drop the "right-truncated/censored". This is how I understand the core idea of nowcasting as a technique, so it is a bit of a redundancy? And I would expect people who understand right truncation in count data to also know about nowcasting?

People do not have a clue what nowcasting is in this context. Lots of people think it means situational awareness etc hence having this explicitly in the title. You are right perhaps we could just drop down to. 

epinowcast: Flexible hierarchical nowcasting

or similar?

**Comment by sbfnk** [comment]
> epinowcast: Flexible hierarchical nowcasting

I like this - the `Description` gives the full detail (right-truncated, Bayesian, etc.). Could add to the end of the description something like: "While the package has been designed with the epidemiological application in mind, it could be applied to any set of right-truncated time-series count data". Even if not we might want to weave in "time series" somewhere as at the moment it just says as "count data" is a bit vague.

**Comment by seabbs** [comment]
The only potential issue is that some people really hate the hierarchical nomenclature and to be fair it gets confusing if you have multiple random effects etc.
